# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'ios-startup-guide' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for ios-startup-guide
  pod 'AFNetworking', '~> 3.0'

  target 'ios-startup-guideTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ios-startup-guideUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
